
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 22 18:02:30 CST 2009
//----------------------------------------------------

package compiladorada;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 11;
  public static final int IDENTIFICADOR = 106;
  public static final int DIVISION = 83;
  public static final int LIMITED = 37;
  public static final int MENOR_QUE = 86;
  public static final int INDEFINIDO = 99;
  public static final int TYPE = 67;
  public static final int SUBTYPE = 62;
  public static final int ALIASED = 7;
  public static final int RAISE = 52;
  public static final int GET = 101;
  public static final int EXPONENTE = 92;
  public static final int RENAMES = 56;
  public static final int UNTIL = 68;
  public static final int CARACTER_LITERAL = 103;
  public static final int TIC = 75;
  public static final int ELSIF = 23;
  public static final int TERMINATE = 65;
  public static final int ETIQUETA_DER = 97;
  public static final int PAR_DER = 76;
  public static final int ALL = 8;
  public static final int INTEGER = 35;
  public static final int MAYOR_QUE = 88;
  public static final int DECLARE = 17;
  public static final int ABORT = 2;
  public static final int PUT = 100;
  public static final int ACCESS = 6;
  public static final int LOOP = 38;
  public static final int PROTECTED = 51;
  public static final int OUT = 46;
  public static final int NOT = 41;
  public static final int TASK = 64;
  public static final int ARRAY = 10;
  public static final int FLOAT = 29;
  public static final int THEN = 66;
  public static final int GOTO = 32;
  public static final int DOS_PUNTOS = 84;
  public static final int FLECHA = 90;
  public static final int PACKAGE = 47;
  public static final int RECORD = 54;
  public static final int REVERSE = 59;
  public static final int BOOLEAN_LITERAL = 105;
  public static final int MOD = 39;
  public static final int WHEN = 70;
  public static final int GENERIC = 31;
  public static final int DIGITS = 20;
  public static final int SELECT = 60;
  public static final int COMA = 80;
  public static final int OTHERS = 45;
  public static final int ABSTRACT = 4;
  public static final int ENTERO_LITERAL = 102;
  public static final int IGUAL = 87;
  public static final int WHILE = 71;
  public static final int USE = 69;
  public static final int REAL_LITERAL = 104;
  public static final int BOOLEAN = 14;
  public static final int DO = 21;
  public static final int FOR = 28;
  public static final int RETURN = 58;
  public static final int MENOS = 81;
  public static final int CONCATENAR = 74;
  public static final int DELAY = 18;
  public static final int ELSE = 22;
  public static final int MAS = 79;
  public static final int PROCEDURE = 50;
  public static final int DISTINTO_DE = 94;
  public static final int ENTRY = 25;
  public static final int DELTA = 19;
  public static final int PRAGMA = 48;
  public static final int ETIQUETA_IZQ = 98;
  public static final int NULL = 42;
  public static final int PUNTO_Y_COMA = 85;
  public static final int PAR_IZQ = 77;
  public static final int EOF = 0;
  public static final int PUNTO = 82;
  public static final int FUNCTION = 30;
  public static final int IS = 36;
  public static final int MENOR_IGUAL_QUE = 96;
  public static final int CONSTANT = 16;
  public static final int BARRA_VERTICAL = 89;
  public static final int BODY = 13;
  public static final int ACCEPT = 5;
  public static final int IN = 34;
  public static final int OR = 44;
  public static final int error = 1;
  public static final int EXIT = 27;
  public static final int IF = 33;
  public static final int OF = 43;
  public static final int ABS = 3;
  public static final int END = 24;
  public static final int REM = 55;
  public static final int REQUEUE = 57;
  public static final int SEPARATE = 61;
  public static final int MULTIPLICACION = 78;
  public static final int CADENA_LITERAL = 107;
  public static final int RANGO = 91;
  public static final int ASIGNACION = 93;
  public static final int BEGIN = 12;
  public static final int CASE = 15;
  public static final int EXCEPTION = 26;
  public static final int NEW = 40;
  public static final int TAGGED = 63;
  public static final int RANGE = 53;
  public static final int MAYOR_IGUAL_QUE = 95;
  public static final int AND = 9;
  public static final int PRIVATE = 49;
  public static final int WITH = 72;
  public static final int XOR = 73;
}

